// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8emSkfo83mArYU-vWYuKcRW4BKfUtbBs',
    appId: '1:1086599505073:web:2e866f2b9731d18be02e90',
    messagingSenderId: '1086599505073',
    projectId: 'what-do-you-want-8a404',
    authDomain: 'what-do-you-want-8a404.firebaseapp.com',
    storageBucket: 'what-do-you-want-8a404.firebasestorage.app',
    measurementId: 'G-ST9EVFYE6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVnNqv-GJ8KFS2sV_OyNR6qPn1b6eiq2c',
    appId: '1:1086599505073:android:9e373690ee1ffe9fe02e90',
    messagingSenderId: '1086599505073',
    projectId: 'what-do-you-want-8a404',
    storageBucket: 'what-do-you-want-8a404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZp-5X7Wksp-P2-MNSqvLaNWSuIFi27xc',
    appId: '1:1086599505073:ios:a9ab3646e81ae01de02e90',
    messagingSenderId: '1086599505073',
    projectId: 'what-do-you-want-8a404',
    storageBucket: 'what-do-you-want-8a404.firebasestorage.app',
    iosBundleId: 'com.example.whatdoyouwant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZp-5X7Wksp-P2-MNSqvLaNWSuIFi27xc',
    appId: '1:1086599505073:ios:a9ab3646e81ae01de02e90',
    messagingSenderId: '1086599505073',
    projectId: 'what-do-you-want-8a404',
    storageBucket: 'what-do-you-want-8a404.firebasestorage.app',
    iosBundleId: 'com.example.whatdoyouwant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8emSkfo83mArYU-vWYuKcRW4BKfUtbBs',
    appId: '1:1086599505073:web:20dad3287620f7bbe02e90',
    messagingSenderId: '1086599505073',
    projectId: 'what-do-you-want-8a404',
    authDomain: 'what-do-you-want-8a404.firebaseapp.com',
    storageBucket: 'what-do-you-want-8a404.firebasestorage.app',
    measurementId: 'G-CD0DLD3CSJ',
  );
}
